spring.application.name=agrosmart
spring.profiles.active=prod

spring.datasource.url=jdbc:postgresql://localhost:5432/agrosmart_db
spring.datasource.username=postgres
spring.datasource.password=Naniko.al56
spring.jpa.hibernate.ddl-auto=update